# Creating NumPy Arrays

In real-world data science, arrays are often created as placeholders,
feature matrices, or numerical ranges for analysis and modeling.
Choosing the correct creation method avoids bugs and inefficiencies.

### Creating Arrays from List

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5]) # 1D array
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])      # 2D array
arr3 = np.array([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]]) # 3D array

print("1D NumPy Array:\n", arr1)
print("2D NumPy Array:\n", arr2)
print("3D NumPy Array:\n", arr3)

1D NumPy Array:
 [1 2 3 4 5]
2D NumPy Array:
 [[1 2 3]
 [4 5 6]]
3D NumPy Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


### Creating Arrays from Scratch

#### mistake
- np.zeros(3, 3)
#### Correct
- np.zeros((3, 3))

function must be a single integer or a tuple of integers, not multiple separate integer arguments. 

In [3]:
zeros = np.zeros((3, 3)) # 3x3 array of zeros
ones = np.ones((2, 4)) # 2x4 array of ones
num = np.full((2, 2), 7) # 2x2 array filled with 7
id_m = np.eye(4) # 4x4 identity matrix
rang = np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)
lins = np.linspace(0, 5, 6) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

print("Array of Zeros:\n", zeros)
print("Array of Ones:\n", ones) 
print("Array filled with 7:\n", num)
print("Identity Matrix:\n", id_m)
print("Array with Range:\n", rang)
print("Array with Linspace:\n", lins)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array filled with 7:
 [[7 7]
 [7 7]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array with Range:
 [1 3 5 7 9]
Array with Linspace:
 [0. 1. 2. 3. 4. 5.]


#### Key Difference
- arange: step-based, may suffer from floating-point issues
- linspace: count-based, guarantees exact number of values

### Checking Array Properties

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape) # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size) # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


### Summary
It explains how to convert Python lists into NumPy arrays, initialize arrays using zeros, ones, and full, and generate numerical ranges using arange and linspace. The notebook also highlights the importance of array shape, size, dimensions, and data types during creation, along with common mistakes.