# Indexing and slicing

## Indexing

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 13)

print(arr[0]) # First element of array
print(arr[-1]) # Last element of array
print(arr[5]) # index 5 element of array

1
12
6


## Slicing

In [3]:
arr = np.array(range(1, 11)) # np.arange

print(arr[:5]) # Same as arr[0:5]
print(arr[4:]) # Same as arr[4:-1]

[1 2 3 4 5]
[ 5  6  7  8  9 10]


Indexing & Slicing returns a view, not a copy! Changes affect the original
array.

In [4]:
# Exemple
arr[4] = 0
print(arr)
arr[5:] = 1
print(arr)

[ 1  2  3  4  0  6  7  8  9 10]
[1 2 3 4 0 1 1 1 1 1]


## Fancy Indexing & Boolean Masking
Fancy and boolean indexing return copies, but assignment through them modifies the original array because NumPy writes directly to the indexed positions.

### Fancy Indexing (Select Multiple Elements)

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
idx = [0, 2, 5] # Indices to select
arr[idx] 

array([1, 3, 6])

### Boolean Masking (Filter Data)

In [6]:
arr = np.arange(1, 21)
mark = arr > 10 # Condition: values greater than 10
arr[mark]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Summary
- Indexing (Same as Python Lists)
- Slicing (Extracting Parts of an Array)
- Indexing & slicing allow efficient data manipulation.
- Fancy indexing & boolean masking help filter and access specific data.
