# Multidimensional Indexing and Axis

- 1D array → 1 axis (axis 0)
- 2D array → 2 axes (axis 0 = rows, axis 1 = columns)
- 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [1]:
import numpy as np

### Check Dimensions

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Number of Dimensions: ", arr1.ndim)

Number of Dimensions:  1


In [3]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])
print("Number of Dimensions: ", arr2.ndim)

Number of Dimensions:  2


In [4]:
arr3 = np.array([[[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]],

                 [[13, 14, 15, 16],
                [17, 18, 19, 20],
        [21, 22, 23, 24]]])
print("Number of Dimensions: ", arr3.ndim)

Number of Dimensions:  3


## 1D array → 1 axis (axis 0)

In [5]:
print(f"Sum of all Elements: {arr1.sum()}") 

Sum of all Elements: 15


## 2D array → 2 axes (axis 0 = rows, axis 1 = columns)

In [6]:
print("Number of Dimensions: ", arr2.ndim)
print(f"Sum of all Elements: {arr2.sum()}") 

# Axis: 0 (Vertical sum) sums each column individually.
print(f"Sum across columns (vertical/Axis 0): {arr2.sum(axis=0)}")

# Axis: 1 (Horizontal sum) sums each row individually.
print(f"Sum across rows (horizontal/Axis 1): {arr2.sum(axis=1)}")


Number of Dimensions:  2
Sum of all Elements: 36
Sum across columns (vertical/Axis 0): [ 6  8 10 12]
Sum across rows (horizontal/Axis 1): [10 26]


## 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [7]:
print("Number of Dimensions: ", arr3.ndim)
print(f"Sum of all Elements: {arr3.sum()}") 

# Axis 0: Collapses across matrices (planes/depth)
print(f"Sum across Planes (Axis 0):\n{arr3.sum(axis=0)}")

# Axis 1: Collapses down the rows (vertical sum within each plane)
print(f"Sum across Rows (Axis 1):\n{arr3.sum(axis=1)}")

# Axis 2: Collapses across the columns (horizontal sum within each plane)
print(f"Sum across Columns (Axis 2):\n{arr3.sum(axis=2)}")


Number of Dimensions:  3
Sum of all Elements: 300
Sum across Planes (Axis 0):
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
Sum across Rows (Axis 1):
[[15 18 21 24]
 [51 54 57 60]]
Sum across Columns (Axis 2):
[[10 26 42]
 [58 74 90]]


Axis tells NumPy the direction in which the operation is performed,
not the dimension that is removed.

## Indexing in Multidimensional Arrays

- access elements using row and column indices.
- also use slicing to extract parts of an array.

### access elements using row and column indices.

In [8]:
print(f"Assecc First Row and First Column: {arr2[0, 0]}") 
print(f"Assecc Second Row and 3th Column: {arr2[1, 2]}")
print(f"Assecc Last Row and last Column : {arr2[-1, -1]}")

Assecc First Row and First Column: 1
Assecc Second Row and 3th Column: 7
Assecc Last Row and last Column : 8


### also use slicing to extract parts of an array

In [9]:
print(f"Assecc All Rows and Columns:\n{arr2[:, :]}")
print(f"Assecc All Rows and First Column: {arr2[:, 0]}")
print(f"Assecc First Row and All Columns: {arr2[0, :]}")
print(f"Assecc Rows(Index 0, 1) and Columns(Index 1, 2):\n{arr2[0:2, 1:3]}")

Assecc All Rows and Columns:
[[1 2 3 4]
 [5 6 7 8]]
Assecc All Rows and First Column: [1 5]
Assecc First Row and All Columns: [1 2 3 4]
Assecc Rows(Index 0, 1) and Columns(Index 1, 2):
[[2 3]
 [6 7]]


## Indexing in 3D Arrays

In [10]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape) # Output: (2, 2, 3) 

(2, 2, 3)


In [11]:
print(f"Access First Layer (Plane):\n{arr3D[0]}") 
print(f"Access Element at [0,0,0]: {arr3D[0, 0, 0]}")
print(f"Access Last Element: {arr3D[-1, -1, -1]}")
print(f"Access Column 1 of the First Layer:\n{arr3D[0, :, 1]}")

Access First Layer (Plane):
[[1 2 3]
 [4 5 6]]
Access Element at [0,0,0]: 1
Access Last Element: 12
Access Column 1 of the First Layer:
[2 5]


### Changing Data Along an Axis
Replace all elements in column 1 with 0

In [12]:
arr2[:, 1:3] = 0
print(arr2)

[[1 0 0 4]
 [5 0 0 8]]


## Summary
- Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)
- Indexing works as arr[row, column] for 2D arrays and arr[depth, row,
column] for 3D arrays
- Slicing allows extracting subarrays
- Operations along axes help efficiently manipulate data without loops