# Broadcasting in NumPy

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations. 
Instead of creating expensive copies of data to match shapes, NumPy "broadcasts" the smaller array across the larger one efficiently.

In [1]:
import numpy as np

## Scalar Broadcasting
The scalar is treated as an array of the same shape.

In [2]:
arr = np.array([1, 2, 3])
result = arr * 2  # 2 is broadcasted to [2, 2, 2]

print("Original Array:", arr)
print("Array * 2:", result)

Original Array: [1 2 3]
Array * 2: [2 4 6]


## Broadcasting with 2D Arrays
Broadcasting works when the trailing dimensions (from right to left) are either equal or one of them is 1.

In [3]:
matrix = np.array([[1, 1, 1], 
                   [2, 2, 2], 
                   [3, 3, 3]])
row_vec = np.array([0, 1, 2])

result = matrix + row_vec  # row_vec is broadcasted down each row

print("Matrix (3x3):\n", matrix)
print("Row Vector (1x3):", row_vec)
print("Result:\n", result)

Matrix (3x3):
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Row Vector (1x3): [0 1 2]
Result:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


## The Rules of Broadcasting
To determine if two arrays are compatible, compare their shapes element-wise, starting from the **right-most** dimension:
1. Are the dimensions equal?
2. Is one of the dimensions 1?

If neither condition is met, NumPy throws a `ValueError`.

In [4]:
a = np.ones((2, 3))
b = np.ones((2,))

try:
    print(a + b)
except ValueError as error:
    print(f"Error: {error}")

Error: operands could not be broadcast together with shapes (2,3) (2,) 


### Summary
- **Efficiency**: Broadcasting avoids creating redundant copies of data in memory.
- **Vectorization** allows you to apply operations to entire arrays at once, greatly
improving performance by utilizing NumPy’s optimized C backend.
- **Broadcasting** enables operations between arrays of different shapes by
automatically stretching the smaller array to match the shape of the larger
array.